#!/bin/bash
##
## MPI submission script for PBS on CRESCENT
## -----------------------------------------
##
## Follow the 6 steps below to configure your job
## 
## STEP 1:
##
## Enter a job name after the -N on the line below:
##
#PBS -N flap_Cl05_40deg
##
## STEP 2:
##
## Select the number of cpus/cores required by modifying the #PBS -l select line below
##
## Normally you select cpus in chunks of 16 cpus
## The Maximum value for ncpus is 16 and mpiprocs MUST be the same value as ncpus.
##
## If more than 16 cpus are required then select multiple chunks of 16
## e.g.	16 CPUs: select=1:ncpus=16:mpiprocs=16
##	32 CPUs: select=2:ncpus=16:mpiprocs=16
##	48 CPUs: select=3:ncpus=16:mpiprocs=16
##	..etc..
##
#PBS -l select=1:ncpus=2:mpiprocs=2
##
## STEP 3:
##
## Select the correct queue by modifying the #PBS -q line below
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q two_day
##
## STEP 4:
##
## Replace the hpc@cranfield.ac.uk email address
## with your Cranfield email address on the #PBS -M line below:
## Your email address is NOT your username
##
#PBS -m abe 
#PBS -M s.fernandez@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
## STEP 5: 
## 
##  Load the default application environment
##  For a specific version add the version number, e.g.
##  module load intel/2016b
##
##module load OpenFOAM/v1612+-foss-2016b  
module load OpenFOAM/v2006-foss-2020a
#
# as for interactive use of OpenFOAM we want to use parafoam or paraview
# we have to set LD_PRELOAD to the GL/GLX libraries this breaks
# batch use as these libraries don't exist on headless compute nodes
# so we unset the LD_PRELOAD variable here
#
unset LD_PRELOAD
#
source $FOAM_BASH
##
## STEP 6: 
## 
## Run MPI code 
##
## The main parameter to modify is your mpi program name
## - change YOUR_EXECUTABLE to your own filename
##  
## For OF you need to pass environment variables to the nodes as you cannot source $FOAM_BASH in the same SSH session used
## by the mpirun command (see -x flags below).
##
mpirun -x LD_LIBRARY_PATH -x FOAM_USER_LIBBIN -x WM_PROJECT_USER_DIR -x PATH -x WM_PROJECT_DIR -x WM_PROJECT_INST_DIR -x MPI_BUFFER_SIZE -machinefile $PBS_NODEFILE -np ${cpus} pimpleFoam -parallel
## Tidy up the log directory
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
