#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

( cd 0012_snappy && cleanCase )
( cd 0012_simple && cleanCase0 )
( cd 0012_pimple && cleanCase0 )

#------------------------------------------------------------------------------
